INSERT INTO task (title, description, status, due_date, created_at, updated_at)
VALUES
  ('Legal Summary', 'Draft case summary for legal proceedings', 'PENDING', '2026-04-05 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Case Analysis', 'Analyze case details and identify key issues', 'PENDING', '2026-04-06 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Legal Strategy Development', 'Develop legal strategy for case handling', 'PENDING', '2026-04-07 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Court Filing Preparation', 'Prepare necessary documents for court filing', 'PENDING', '2026-04-08 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Client Meeting Preparation', 'Prepare materials for client meeting regarding case progress', 'PENDING', '2026-04-09 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Case Files Review', 'Review and update case files', 'PENDING', '2026-03-22 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Evidence Preparation', 'Prepare evidence for court hearing', 'PENDING', '2026-03-17 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Team Coordination', 'Coordinate with legal team for case strategy', 'PENDING', '2026-03-04 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Document Drafting', 'Draft legal documents and motions', 'PENDING', '2026-03-05 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Client Communication', 'Communicate with clients regarding case updates', 'PENDING', '2026-03-06 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Court Appearance Preparation', 'Prepare for upcoming court appearances', 'PENDING', '2026-03-07 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Legal Research', 'Conduct legal research for case precedents', 'PENDING', '2026-03-08 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Case Strategy Meeting', 'Hold strategy meeting with legal team', 'PENDING', '2026-03-09 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Witness Coordination', 'Coordinate with witnesses for testimony preparation', 'PENDING', '2026-03-10 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Evidence Review', 'Review evidence for case strength assessment', 'PENDING', '2026-03-11 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Legal Briefing', 'Prepare legal briefing for court presentation', 'PENDING', '2026-03-12 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Case Management', 'Manage case timelines and deadlines', 'PENDING', '2026-03-13 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Legal Consultation', 'Consult with legal experts for case insights', 'PENDING', '2026-03-14 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Court Document Filing', 'File necessary documents with the court', 'PENDING', '2026-03-15 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Case Review Meeting', 'Review case progress with legal team', 'PENDING', '2026-03-16 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Legal Compliance Check', 'Ensure all case actions comply with legal standards', 'PENDING', '2026-03-17 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Client Follow-up', 'Follow up with clients for additional information', 'PENDING', '2026-03-18 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Case Outcome Analysis', 'Analyze potential outcomes of the case', 'PENDING', '2026-03-19 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Legal Training Session', 'Conduct training session for junior legal staff', 'PENDING', '2026-03-20 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Court Appearance Follow-up', 'Follow up on court appearance outcomes and next steps', 'PENDING', '2026-03-21 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Case Documentation', 'Organize and maintain case documentation', 'PENDING', '2026-03-22 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Final Case Review', 'Conduct final review of all case materials', 'PENDING', '2026-03-23 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Case Closure Preparation', 'Prepare for case closure and documentation finalization', 'PENDING', '2026-03-24 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Post-Closure Follow-up', 'Follow up on post-closure actions and client feedback', 'PENDING', '2026-03-25 17:35:45', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
